### ISSUE TITLE
Look up synsets by WNDB offset and POS

### ISSUE THREAD

**Issue by goodmami** [goodmami/wn#119]
It would be convenient if synsets could be looked up by the old WNDB offset and pos. This might be feasible because these offsets are encoded in synset IDs. If not, there's just a lookup error. Even the OMW wordnets use the PWN 3.0 offsets in their IDs, so this can work for non-PWN synsets.

First is how to define the conversion from offset and pos to identifier. This appears to be `"{lexicon_id}-{offset:08}-{pos}"` in all current cases except OdeNet (which uses non-padded numbers, e.g., `odenet-1-n`), but for OdeNet these are not byte offsets. This format might be a useful default, but in the future we might allow a format in the index. For example:

```toml
[pwn]
  label = "Princeton WordNet"
  language = "en"
  license = "https://wordnet.princeton.edu/license-and-commercial-use"
  synset_identifier_format = "pwn-{offset:08}-{pos}"
  [pwn.versions."3.1"]
    url = "https://github.com/bond-lab/omw-data/releases/download/v1.3/pwn31.tar.xz"
  [pwn.versions."3.0"]
    url = "https://github.com/bond-lab/omw-data/releases/download/v1.3/pwn30.tar.xz"
```

This might need to be redefined per version, but let's decide when we get there.

The next issue is the API design. It would be great to just reuse `Wordnet.synset()` with different parameters, e.g. `Wordnet.synset(offset=1740, pos='n')`, but that would break the current API where there must be a positional argument for the ID. Also, it's not honest as offsets have no meaning in an LMF-based lexicon.

Maybe a function for converting them, or a function factory for generating them per lexicon:

```python
>>> def make_synset_id_formatter(fmt='{prefix}-{offset:08}-{pos}', **kwargs):
...     def format_id(**_kwargs):
...         return fmt.format(**kwargs, **_kwargs)
...     return format_id
... 
>>> format_pwn = make_synset_id_formatter(prefix='pwn')
>>> format_pwn(offset=1740, pos='n')
'pwn-00001740-n'
>>> wn.synset(format_pwn(offset=1740, pos='n'))
Synset('pwn-00001740-n')
```
