### ISSUE TITLE
Allow mirrors to be defined in the index

### ISSUE THREAD

**Issue by goodmami** [goodmami/wn#142]
Several wordnet projects have changes that will require some new features in the index.

* The OMW English Wordnet was misnamed the Princeton WordNet previously. The old and new data should be renamed, along with the identifiers and versions (e.g., `pwn:3.0` -> `wn30:1.4+omw`). When someone uses the old identifier, a warning should be issued as it redirects to the new resource.
* It might also be useful to have a general mechanism for displaying messages when someone downloads a wordnet. One use for this is to recommend users of the upcoming OWN-PT wordnet to also get the OWN-EN wordnet to go along with it.
* There have been some reliability issues with servers hosting wordnets (see #141), so it would be good to be able to specify a mirror in case one server times out.

These changes might look like this:

```toml
[pwn]
  warn = "This project has been renamed. See https://... for more information."
  [pwn.versions."3.0"]
    redirect = "wn30:1.4+omw"
  [pwn.versions."3.1"]
    redirect = "wn31:1.4+omw"

[wn30]
  label = "OMW English Wordnet 3.0"
  [wn30.versions."1.4+omw"]
    url = "https://..."

[wn31]
  label = "OMW English Wordnet 3.1"
  [wn31.versions."1.4+omw"]
    url = "https://..."

[ewn]
  label = "Estonian Wordnet"
  # ...
  [ewn.versions.2020]
    warn = "The Open English WordNet is now under the identifier 'oewn'. See https://... for more information."
    redirect = "oewn:2020"

[oewn]
  label = "Open English WordNet"
  language = "en"
  license = "https://creativecommons.org/licenses/by/4.0/"
  [oewn.versions.2020]
    urls = [
      "https://en-word.net/static/english-wordnet-2020.xml.gz",
      "https://...",
    ]
  [oewn.versions.2019]
    urls = [
      "https://en-word.net/static/english-wordnet-2019.xml.gz",
      "https://...",
    ]
```
