### ISSUE TITLE
Load project index from a TOML file

### ISSUE THREAD

**Issue by goodmami** [goodmami/wn#52]
Using TOML means another dependency, but it's a pretty standard one these days, like setuptools.

This issue (or a similar solution) is required by #43. Below illustrates my proposed schema (and assuming #51 is resolved):

```toml
[ewn]
label = "Open English Wordnet"
language = "en"
license = "https://creativecommons.org/licenses/by/4.0/"

[ewn.versions.2019]
url = "https://en-word.net/static/english-wordnet-2019.xml.gz"

[ewn.versions.2020]
url = "https://en-word.net/static/english-wordnet-2020.xml.gz"
```

It would be nice to just have `ewn.2020`, etc., for each version, but then version names are competing for the project namespace (meaning a version couldn't be called "label", "language", or "license", but we might want to expand that list in the future). Putting it in its own "versions" namespace lets it be anything.
